# This is a workflow to test and deploy our demo app.

name: Demo CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DEMO_HOME: /home/runner/work/SDE-project/SDE-project/
  PYTHONPATH: /home/runner/work/SDE-project/SDE-project/
#  CONNECTION_STRING: ${{secrets.CONNECTION_STRING}}
  GAME_MONGO_PW: ${{secrets.GAME_MONGO_PW}}
  CLOUD_MONGO: ${{secrets.CLOUD_MONGO}}
  echo: ${{secrets.echo}}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: pa_deploy
    # environment: heroku-deploy

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install MongoDB
        uses: supercharge/mongodb-github-action@1.8.0

      - name: Install Python packages.
        run: pip install -r requirements-dev.txt

      - name: Run Python tests.
        run: make all_tests
        
      - name: Deploy to PythonAnywhere
        run: ./deploy.sh
        env:
          SDE_PA_PWD: ${{secrets.SDE_PA_PWD}}
        
